config/routes.rb
B2::Application.routes.draw do
  devise_for :users

  resources :users
  resources :customers do
    resources :invoices
  end

  root to: 'customers#index'

end

app/models/ability.rb
# Adapted from https://github.com/ryanb/cancan/wiki/defining-abilities
class Ability

  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superuser?
      can :manage, :all
    else
      can :manage, Customer, user_id: user.id
      can :manage, Invoice, customer: { user_id: user.id } # https://github.com/ryanb/cancan/wiki/Nested-Resources
    end
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user

  has_many :invoices, dependent: :destroy
  
  accepts_nested_attributes_for :invoices, :reject_if => :all_blank, :allow_destroy => true
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :name
  belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :superuser

  # attr_accessible :title, :body

  has_many :customers

  def authorized_customers
    if superuser?
      Customer.where(true) # return as AREL, to be consistent with...
    else
      customers # ...the plain, has_many association
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :get_user

  # Rescue from load_and_authorize_resource calls in controllers
  rescue_from CanCan::AccessDenied do |exception|
    render file: "#{Rails.root}/public/403", formats: [:html], status: 403, layout: false
  end

private

  def get_user
    @user = current_user
  end
  
end

app/controllers/customers_controller.rb
# This controls a nested resource, because every Customer belongs to a User.
# The current user can see only his customers.
class CustomersController < ApplicationController
  load_and_authorize_resource
  
  # GET /customers
  # GET /customers.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/invoices_controller.rb
# This controls a nested resource, because every Invoice belongs to a Customer.
# Only its customer can see an invoice.
class InvoicesController < ApplicationController
  load_and_authorize_resource :customer
  load_and_authorize_resource :invoice, through: :customer # https://github.com/ryanb/cancan/wiki/Nested-Resources

  # GET /invoices
  # GET /invoices.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    respond_to do |format|
      if @invoices.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update_attributes(params[:customer])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to customer_invoices_url(@customer) }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @users = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User #{@user.email} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def body_class(class_name = "default_class")
    content_for(:body_class, class_name)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= form_for @customer do |f|
  - if @customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      %ul
        - @customer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .actions
    = f.submit 'Save'

app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

app/views/customers/index.html.haml
- body_class("customers_index_page")

%h1 Listing customers

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @customers.each do |customer|
    %tr
      %td= customer.name
      %td= link_to 'Show', customer
      %td= link_to 'Edit', edit_customer_path(customer)
      %td= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New customer', new_customer_path

app/views/customers/new.html.haml
%h1 New customer

= render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @customer.name

= link_to 'Edit', edit_customer_path(@customer)
\|
= link_to 'Back', customers_path

app/views/invoices/_form.html.haml
= form_for([@customer, @invoice]) do |f|
  -#- if @invoice.errors.any?
  -#  #error_explanation
  -#    %h2= "#{pluralize(@invoice.errors.count, "error")} prohibited this invoice from being saved:"
  -#    %ul
  -#      - @invoice.errors.full_messages.each do |msg|
  -#        %li= msg
  -#
  -#.field
  -#  = f.label :name
  -#  = f.text_field :name
  -#
  -#.field
  -#  = f.label :issue_date
  -#  = f.date_field :issue_date
  -#
  -#.field
  -#  = f.label :service_date
  -#  = f.date_field :service_date
  -#
  -#.field
  -#  = f.label :total_charge
  -#  = f.number_field
  -#
  .actions
    = f.submit 'Save'

app/views/invoices/edit.html.haml
%h1 Editing invoice

= render 'form'

= link_to 'Show', customer_invoice_path(@customer, @invoice)
\|
= link_to 'Back', customer_invoices_path(@customer)

app/views/invoices/index.html.haml
- body_class("customer_invoices_index_page")

%h1 Invoices

%table
  %tr
    %th Name
    %th Service Date
    %th Issue Date
    %th
    %th
    %th

  - @invoices.each do |invoice|
    %tr
      %td= invoice.name
      %td= invoice.service_date
      %td= invoice.issue_date
      %td= link_to 'Show', customer_invoice_path(@customer, invoice)
      %td= link_to 'Edit', edit_customer_invoice_path(@customer, invoice)
      %td= link_to 'Destroy', customer_invoice_path(@customer, invoice), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New invoice', new_customer_invoice_path(@customer)

app/views/invoices/new.html.haml
%h1 New invoice

= render 'form'

= link_to 'Back', customer_invoices_path(@customer)

app/views/invoices/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @invoice.name

= link_to 'Edit', edit_customer_invoice_path(@customer, @invoice)
\|
= link_to 'Back', customer_invoices_path(@customer)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:body_class) %>">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email

  .field
    = f.label :password
    = f.password_field :password
    
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New user', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path